export default {
  MAIN: '/',
  SIGN_IN: '/sign-in',
  PROGRAM: '#program',
  PRIZES: '#prizes',
  VOTING: '#voting',
  NOMINATIONS: '#nominations',
  FEEDBACK: '#feedback',
  WINNERS: '#winners',
  RATING: '#rating',
  FAQ: '#faq',
  USER_AGREEMENT: '/documents/user-agreement.pdf',
  PRIVACY_POLICY: '/',
  BEST_DIGITAL_PROJECT: '/applications/best-digital-project',
  BEST_PROJECT: '/applications/best-project',
  BEST_MENTOR: '/applications/best-mentor',
  BEST_EMPLOYEE: '/applications/best-employee',
  VOTE: {
    BEST_PROJECT: '/vote/best-project',
    BEST_DIGITAL_PROJECT: '/vote/best-digital-project',
    BEST_EMPLOYEE: '/vote/best-employee',
    BEST_MENTOR: '/vote/best-mentor',
    PRESIDENT: '/vote/expert/president',
    RATING: '/vote/expert/rating',
  },
  BROADCAST: '/broadcast',
};
